version: '3.3'
services:
  app:
    build: ./
    command: npm run dev
    ports:
      - "5005:5005"
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
